FROM nvidia/cuda:8.0-cudnn6-runtime

RUN apt-get clean && apt-get update && apt-get install -y locales sudo
RUN locale-gen ko_KR.UTF-8
ENV LANG ko_KR.UTF-8
ENV LANGUAGE ko_KR.UTF-8
ENV LC_ALL ko_KR.UTF-8

ENV TMP_DIR /tmp/set_env 
RUN mkdir $TMP_DIR
WORKDIR $TMP_DIR
COPY . ./

RUN ./set_env_for_ubuntu.sh

WORKDIR /



