ARG cuda_version=8.0
ARG cudnn_version=5

FROM nvidia/cuda:${cuda_version}-cudnn${cudnn_version}-runtime

RUN apt-get clean && apt-get update && apt-get install -y locales sudo
RUN locale-gen ko_KR.UTF-8
ENV LANG ko_KR.UTF-8
ENV LANGUAGE ko_KR.UTF-8
ENV LC_ALL ko_KR.UTF-8

ENV TMP_DIR /tmp/set_env 
RUN mkdir $TMP_DIR
WORKDIR $TMP_DIR
COPY . ./

WORKDIR /

RUN ./set_env_for_ubuntu.sh



